### PR TITLE
CI: Update CPython on macOS

### PR DESCRIPTION
**Pull request by nicoonoclaste**

### CODE REVIEW

**Review by AstraLuma — APPROVED** [review]
lgtm

the pyenv that gets shipped on cirrus mac doesn't always track with PSF latest--I've had trouble in the past with figuring out what versions exactly are available.

**Review by AstraLuma — CHANGES_REQUESTED** [review]
Errr... I should have looked at the test results first.

They demonstrate exactly what I'm talking about.

**Comment by nicoonoclaste** [comment]
@AstraLuma I was aware that those CPython versions aren't yet available, this got split off #195 so as not to hold up the update on Linux and Windows.

**Comment by nicoonoclaste** [comment]
bors try

**Comment by AstraLuma** [comment]
bors d+

**Comment by nicoonoclaste** [comment]
bors r=astraluma

**Pull request merged**
