### PR TITLE
tests/rotate: Test trigonometric invariance (+360° changes nothing)

### PR DESCRIPTION
**Pull request by nbraud**
This is probably somewhat-overkill, but I realised it was something important to check, that was missing

### CODE REVIEW

**Comment by nbraud** [comment]
This should be retested once #119 is merged (since it uses `Vector2.isclose`)

**Comment by astronouth7303** [comment]
Call me paranoid, mind merging in master to double check it's fine?

**Comment by nbraud** [comment]
@astronouth7303 Done.

In general, I really would prefer if we reran CI (against a merge to `master`) whenever `master changes, but I guess that's something for #117.

**Comment by nbraud** [comment]
Urg, I had tested locally, but of course that didn't run with the CI profile for Hypothesis.
We really need something to automatically re-run the tests.

**Comment by astronouth7303** [comment]
Puppy like bors for that.

**Comment by nbraud** [comment]
@astronouth7303 I'm aware, I also like bors reasonably well.

It does more than “just” rerunning CI though, as the (preferred?) workflow with it is:
- maintainer reviews, leaves a `@bors r+` command (positive review);
- Bors does the merge in a temporary branch;
- CI runs on the branch, goes green;
- Bors pushes the merge to `master`.

Given that it changes your workflow, and that I'm not a maintainer, I didn't want to push for it, but it _does_ guarantee that nothing CI-breaking lands into `master`.

**Comment by nbraud** [comment]
@astronouth7303 In case you didn't notice, I fixed the new tests so this should be good to go.

**Pull request merged**
