### PR TITLE
Drop subclassing support

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Document that subclassing isn't supported.
- [x] Drop the subclassing testsuite.
- [x] Drop the subclassing support.
- [x] Rename `Vector2` to `Vector`.
  Avoid breaking backwards-compatibility by adding a `Vector2` alias.
- [x] Rename `vector2.py` to `vector.py`.

Closes #144 (this is an alternative proposal)

### CODE REVIEW

**Comment by nbraud** [comment]
I will measure the (hopefully positive) performance impact tomorrow  :)

**Comment by astronouth7303** [comment]
Is there a reason to not just rename `vector.py` to `__init__.py`?

**Comment by astronouth7303** [comment]
@nbraud

**Comment by nbraud** [comment]
@astronouth7303 I have no particular opinion one way or another, I didn't particularly want to add extra changes, but I can easily do that.

**Comment by nbraud** [comment]
@astronouth7303 Done.

**Pull request merged**
