### PR TITLE
tests: Test that 2-ary methods work with vector-likes

### PR DESCRIPTION
**Pull request by nbraud**
Depends on #91

### CODE REVIEW

**Comment by nbraud** [comment]
Is there a blocker on this?  #91 was merged.

**Comment by nbraud** [comment]
PS: I just added a test for the property you mentioned in #91

**Comment by astronouth7303** [comment]
At this point, the only reason I'm not merging it is #85.

**Comment by nbraud** [comment]
OK, so what's holding up #85?

**Comment by nbraud** [comment]
PS: That shouldn't conflict with #85, since it's only adding `test_binop_vectorlike`.
(Github displays a large diff because it doesn't detect that commits that belonged to #91 got merged.)

**Comment by astronouth7303** [comment]
Oh, if it doesn't conflict, then ok.

**Pull request merged**
