### PR TITLE
CI: Update Python 3.6 and 3.7 on macOS, add Python 3.8

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
This will have a trivial conflict with #182.

**Comment by nbraud** [comment]
bors try

**Comment by nbraud** [comment]
CI passed on bors' test merge, this should be good to go.

**Comment by nbraud** [comment]
Looks like Homebrew updated their version of `pyenv` overnight, so this is unblocked.

**Comment by nbraud** [comment]
The clouds are stormy today, both CI failures were caused by GCP errors:
- `FreeBSD PYTHON:3.7`:
  - Failed to stop: Internal error. Please try again or contact Google Support. (Code: '1805264636142802904')
  - Failed to stop: Internal error. Please try again or contact Google Support. (Code: '8021641625323381322')
- `Windows python:3.6-windowsservercore-1809`:  
  Failed to stop: Internal error. Please try again or contact Google Support. (Code: '3893227014170968840')

**Comment by astronouth7303** [comment]
Bors r+

**Pull request merged**
