### PR TITLE
Make (non-null) vectors truth-y

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
Not sure whether to add a test, or what it should be.

The only thing I can think of is `bool(v) == (v.x == 0 and v.y == 0)`, and that's pretty much literally a copy-paste of the code that implements `__bool__`.

**Comment by astronouth7303** [comment]
Given it's used everywhere, I'm going to consider it tested.

**Comment by nbraud** [comment]
@astronouth7303 OK, feel free to `bors r+` if you reviewed.

**Comment by nbraud** [comment]
bors r=astronouth7303

**Pull request merged**
