### PR TITLE
tests/typing: Replace hardcoded inputs with Hypothesis parameters

### PR DESCRIPTION
**Pull request by nbraud**
The testsuite now catches the [potential bug](https://github.com/ppb/ppb-vector/pull/95#discussion_r244650431) discussed in #95

### CODE REVIEW

**Comment by nbraud** [comment]
@astronouth7303 Following our conversation last night, I tried to use Hypothesis in `test_typing.py` and it turned out not to make it more complicated; in fact, I think the type annotations are a readability improvement.
What do you think?

**Comment by nbraud** [comment]
The CI failure is unrelated, and I added it in #99 as an explicit example so we can fix it there.

**Comment by nbraud** [comment]
There's a fix in #99 now

**Comment by astronouth7303** [comment]
Naughty! Naughty! There's changes to the signature of `__init__()` mixed in this testing PR! :stuck_out_tongue: However, this is more Pythonic.

The tests themselves seem solid.

**Comment by nbraud** [comment]
@astronouth7303 Yeah, it seemed more reasonable to support building a vector from a vector-like than hack around the lack of support, though I just realised I could have used `st.builds(V1.convert, _)`.

Anyhow, I assumed you would look at the commits in the PR, and it's in a separate commit so it can easily be pulled out if you'd rather have it be a separate discussion.

**Comment by nbraud** [comment]
PS: Now that the fix for the CI failure is merged, can you re-run the build/tests?

**Comment by nbraud** [comment]
OK, #102 should finally(!) squash that CI failure.

**Comment by nbraud** [comment]
CI is now green.

**Comment by nbraud** [comment]
Urg, I forgot that Github gets confused when one pushes a merge commit to a PR branch; going to rebase and force-push...

**Comment by nbraud** [comment]
Since this wasn't merged yet, I included some conversion test cleanups.
The tests caught that `dict(some_vector2)` didn't work, so I also implemented the `mapping` protocol.

**Comment by nbraud** [comment]
Rebased because of the last merges, added one more test (see last commit: 
2f2bfdb)

**Pull request merged**
