### PR TITLE
Cirrus CI: upload build artifacts to Github and (test) PyPI

### PR DESCRIPTION
**Pull request by nbraud**
- `requirements-upload.txt` taken from pursuedpybear;
- `.ci/upload-build.sh` inspired by Cirrus CI's [documentation];
- upload task uses account `pursuedpybear` on Github and `test.pypi.org`.

[documentation]: https://cirrus-ci.org/examples/#release-assets

### CODE REVIEW

**Comment by nbraud** [comment]
- [ ] @pursuedpybot needs to be invited to @ppb and granted write access to `ppb-vector` (or at least its release artifacts).
- [ ] [`pursuedpybot`](https://test.pypi.org/user/pursuedpybot/) needs to be granted upload access to `ppb-vector` (on `test.pypi.org`)

**Comment by astronouth7303** [comment]
* Let's convert pursuedpybot into an app under the ppb organization
* API keys are coming down the PyPI pipeline, per https://github.com/pypa/warehouse/issues/994#issuecomment-493171700

**Comment by nbraud** [comment]
@astronouth7303 I do not believe I have the required level of access to create an app under the PPB organisation.

**Comment by nbraud** [comment]
Re: PyPI API keys

> per-user API keys as an alternative form of multifactor authentication

:scream_cat: 

> - Each user who has upload permissions for a specific project will be able to generate API tokens via the Warehouse web UI with upload permissions for that specific project.
> - Each user will be able to view, manage, revoke, and delete their own previously generated API tokens via the Warehouse web UI.

API tokens will still be owned by specific users, so we will still need a PyPI user for the organisation.

**Comment by astronouth7303** [comment]
> Implement support for per-User and per-Project API Keys as PyPI API authentication tokens

**Comment by nbraud** [comment]
So, any feedback on whether we want this, and whether the 2 `pursuedpybot` machine users have the necessary access?
If so, I'd like to merge and cut a release candidate so:
1. we can test the latest changes in PPB itself before comiting to 1.0;
2. we can test the release automation (against `test.pypi.org`) for a pre-release.

Per the discussion on Discord, we cannot currently avoid having a machine user for PyPI, and it's not obvious it is possible for a Github App; it might be possible by registering an app and [manually acquiring an OAuth token], but that will require some thought and development effort.

[manually acquiring an OAuth token]: https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization

**Comment by astronouth7303** [comment]
Ok, after discussions.

Yes, this is a thing we want.

The current incarnation is fine. A full github app would require infra and no thanks right now.

Let's try to use this for the current release cycle.

**Pull request merged**
