### PR TITLE
tests/rotate: Loosen tolerances on test_rotation_stability

### PR DESCRIPTION
**Pull request by nicoonoclaste**
Caused a CI failure in #195.

### CODE REVIEW

**Review by AstraLuma — APPROVED** [review]
bors r+

**Comment by nicoonoclaste** [comment]
bors r=astraluma

Looks like the container that test ran in died midway-through

**Comment by nicoonoclaste** [comment]
bors r=astraluma

Cirrus seems to be having a really bad day  :sob:

**Comment by nicoonoclaste** [comment]
bors r=astraluma

Let's see whether Cirrus is less-broken today

**Pull request merged**
