### PR TITLE
CI: Upgrade to current versions of CPython and PyPy

### PR DESCRIPTION
**Pull request by nicoonoclaste**
- [x] Add CI environments for CPython 3.9 and 3.10-rc
- [x] Configure Bors to require CI to pass on 3.9
- [x] Add a CI environment for PyPy (w/ Python 3.7)

### CODE REVIEW

**Comment by pathunstrom** [comment]
:/ Those homebrew dependencies are less than good. This looks good, I guess we just wait until those versions work?

**Comment by nicoonoclaste** [comment]
> :/ Those homebrew dependencies are less than good. This looks good, I guess we just wait until those versions work?

I split-off the FreeBSD and macOS updates to 2 separate PRs

**Comment by nicoonoclaste** [comment]
bors try

**Review by AstraLuma — APPROVED** [review]
bors r+

**Comment by nicoonoclaste** [comment]
bors r=astraluma

**Comment by pathunstrom** [comment]
bors retry

**Comment by nicoonoclaste** [comment]
bors retry

*sighs, goes scream into the void.*

**Comment by pathunstrom** [comment]
We're experimenting with some levers to try to make this better. . . not going well.

**Pull request merged**
