### PR TITLE
CI: Add CPython 3.9 under FreeBSD

### PR DESCRIPTION
**Pull request by nicoonoclaste**
Split-off from #195

### CODE REVIEW

**Comment by nicoonoclaste** [comment]
bors try

**Comment by pathunstrom** [comment]
Is 3.9 really not yet in the FreeBSD repositories?

**Comment by AstraLuma** [comment]
It wasn't in october, it apparently is now.

**Comment by AstraLuma** [comment]
bors d+

**Comment by nicoonoclaste** [comment]
bors r=astraluma

**Pull request merged**
