### PR TITLE
Add myself to the contributors list

### PR DESCRIPTION
**Pull request by nbraud**
@astronouth7303 suggested I should do that.

### CODE REVIEW

**Comment by nbraud** [comment]
@pathunstrom How are the contributor and maintainer lists supposed to be sorted?  It's not very obvious from the current document.

**Comment by pathunstrom** [comment]
@nbraud There's not a given order, it's mostly been in order of contribution over in ppb/pursuedpybear, but nothing specific.

**Comment by nbraud** [comment]
@pathunstrom OK; should I sort it alphabetically then?

**Comment by nbraud** [comment]
@pathunstrom OK, then this should be good to go.

**Pull request merged**
