### PR TITLE
Fixing CI

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
OK, I'm entirely mystified: the CI for #111 ([build 276](https://travis-ci.org/ppb/ppb-vector/jobs/488539106#L546-L563)) and for #110 ([build 273](https://travis-ci.org/ppb/ppb-vector/jobs/481852204#L514-L531)) fail on Python 3.6 with the same error, that I cannot reproduce here:
```
$ pytest --hypothesis-profile ci
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/pytest", line 7, in <module>
    from pytest import main
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest.py", line 14, in <module>
    from _pytest.fixtures import fillfixtures as _fillfuncargs
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/fixtures.py", line 20, in <module>
    from _pytest import nodes
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/nodes.py", line 14, in <module>
    from _pytest.mark.structures import MarkInfo
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/__init__.py", line 8, in <module>
    from .structures import EMPTY_PARAMETERSET_OPTION
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/structures.py", line 323, in <module>
    class MarkInfo(object):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/structures.py", line 326, in MarkInfo
    _marks = attr.ib(converter=list)
TypeError: attrib() got an unexpected keyword argument 'converter'
The command "./test.sh" exited with 1.
```

**Comment by nbraud** [comment]
In all 3 cases, the version of pytest installed is 3.10.1.

**Comment by nbraud** [comment]
Looks like `pytest` needs a new-enough version of `attrs` but specifies an insufficient version in its `setup.py`.  This has happened [before](https://github.com/pytest-dev/pytest/issues/3280).

**Comment by astronouth7303** [comment]
Travis makes me sad, and I wish there was a good alternative.

**Comment by nbraud** [comment]
@astronouth7303 To be fair, I think this time it wasn't entirely its fault  :(

**Comment by nbraud** [comment]
Looks like it [might be `pip`'s fault](https://github.com/pypa/pip/issues/5335), actually.
This is weird and I really shouldn't track it down, but I want to be sure it doesn't reoccur.

**Pull request merged**
