### PR TITLE
CI: Update for CPython 3.8

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
bors try

**Comment by nbraud** [comment]
- FreeBSD: the `python38` port was added on 2019-11-02, updated 2019-11-07, and the binary package was available on the same day; not sure why the install failed...
- macOS: Homebrew ships pyenv v1.2.13, and the definition for CPython 3.8 was added in 1.2.14.

I'm going to split off the FreeBSD- and macOS-related changed in separate PRs so this can go in now.

**Comment by astronouth7303** [comment]
Bors r+

**Comment by nbraud** [comment]
Rudest  :(

**Comment by nbraud** [comment]
bors r=astronouth7303

**Comment by nbraud** [comment]
bors r=astronouth7303

Sorry for the noise, I noticed I had forgotten to update the classifiers in `setup.cfg`.

**Pull request merged**
