### PR TITLE
Cirrus CI: Run tests under PyPy 3.6

### PR DESCRIPTION
**Pull request by nbraud**
Follow-up on #121

### CODE REVIEW

**Comment by nbraud** [comment]
Oops, I didn't notice because it was marked as an allowed failure in Travis (which doesn't report status on individual jobs), but I think `tests/memory` is broken under PyPy (because `pympler` doesn't work there)  :(

**Comment by astronouth7303** [comment]
Indeed it doesn't.

I'm pretty ok with not running that test under pypy? It's a test for performance, not correctness, so I consider it significantly less important. That is, I care much more that it works under PyPy than I do that it has the same performance characteristics.

**Comment by nbraud** [comment]
Sure, I think skipping that test under PyPy (or at least allowing it to fail) is the right thing to do; I just left a comment so I'll know about it when I pick it up again.

**Comment by nbraud** [comment]
@astronouth7303 I just fixed the merge conflict (happened since #133 also touched the list of container images), this should now be good to go.  :)

**Pull request merged**
