### PR TITLE
tests/utils: Freeze all the operators sets

### PR DESCRIPTION
**Pull request by nbraud**
Split off from #146.

### CODE REVIEW

**Comment by nbraud** [comment]
Fails with a `mypy` error:
```
tests/benchmark.py:19: error: <nothing> has no attribute "__name__"
```

This sounds possibly like a bug?  :/

**Comment by astronouth7303** [comment]
Is there a reason for the change? Or just most correct semantically?

**Comment by nbraud** [comment]
I accidentally mutated one of those from a test, which of course had all sorts of hilarious results.
So, yes, semantic correctness and removing feetguns.

**Pull request merged**
