### PR TITLE
tests/memory: Disable test_object_size under CPython 3.8

### PR DESCRIPTION
**Pull request by nbraud**
See https://github.com/pympler/pympler/issues/74

### CODE REVIEW

**Comment by nbraud** [comment]
@pathunstrom I made a tracking issue for re-enabling it: https://github.com/ppb/ppb-vector/issues/140

**Comment by nbraud** [comment]
@pathunstrom Oh, I'm kinda dumb; bors will only wait for the required status checks, which doesn't include 3.8-rc...
In any case, looking at Cirrus, the test passed at least [on Linux](https://github.com/ppb/ppb-vector/runs/88400319)

**Comment by pathunstrom** [comment]
I'm not worried about clean passing 3.8 yet. It's nice to know that things keep working, though.

**Pull request merged**
