### PR TITLE
WiP: in-Python documentation

### LINKED ISSUE #109: Improve docstrings & type signatures
From #106 :

> That's indeed not very nice. OTOH, help() is currently useless on Vector2 because:
>
> - Type constructs like VectorLike are expanded into an illegible mess.
> - Description & documentation are in the README rather than in docstrings.
>
> I think it would be worth fixing, but it's way out of scope for this PR.

### PR DESCRIPTION
**Pull request by nbraud**
Closes #109 

- [ ] Move documentation from `README` to docstrings.
- [ ] Improve the treatment of complex types such as `VectorLike` or `Realish`.
- [ ] Generate a documentation page from the docstrings (in CI), link to it from `README`.

### CODE REVIEW

**Comment by astronouth7303** [comment]
I'm ok with removing the documentation from the readme if it's available elsewhere online. The readme only needs a summary in that case (eg, full API docs produced with Sphinx).

**Comment by nbraud** [comment]
@pathunstrom OK, is this the next #85?  Should I just disregard the negative review and go with Jamie's recommendation?

**Comment by nbraud** [comment]
Rebased to solve the merge conflict.

**Comment by nbraud** [comment]
Obsoleted by #128

**Pull request closed without merging**
