### PR TITLE
Commit to semantic versioning

### PR DESCRIPTION
**Pull request by nbraud**
Also snuck in 2 minor changes to `README.md`, as I didn't want to deal with conflicting PRs:
- call the RTD docs “API reference”;
- use complete sentences.

### CODE REVIEW

**Comment by nbraud** [comment]
@pathunstrom Sorry, I accidentally opened the PR too early (i.e. before I had commited the relevant changes  >_>')

@astronouth7303 I got a :+1: from Piper on Discord, re: semver, but I would prefer to have your opinion before comiting to it.

**Comment by astronouth7303** [comment]
Yes semver good

**Comment by nbraud** [comment]
bors r=astranouth5303,pathunstrom

**Comment by nbraud** [comment]
@astronouth7303 Why would we call it 2.0, if it's the same thing but faster?

**Pull request merged**
