### PR TITLE
Bump version to Release Candidate 1

### PR DESCRIPTION
**Pull request by astronouth7303**
No major bugs have cropped up, just some optional lapses in functionality.

### CODE REVIEW

**Comment by nbraud** [comment]
@astronouth7303 Can we merge #176 first?  That addresses the last bit of feedback that was given on #23.

**Comment by astronouth7303** [comment]
Things like #168, #171, and #174. These are improvements and expansions to the API that aren't part of any MVP or other functionality goals, and affect existing functionality. In other words, they're perfect for inclusion in a minor release.

**Comment by nbraud** [comment]
@astronouth7303 Ah, yes.

**Comment by nbraud** [comment]
bors r+

@astronouth7303 I'm about to go have lunch; I can deal with the release when I come back, unless you get to it first.

**Pull request merged**
