### PR TITLE
Add & use class-level constants

### PR DESCRIPTION
**Pull request by nicoonoclaste**
- Add class-level constants `Vector.u` and `v` for each axis.
- Replace homemade constants in `tests/utils` with those.
- Replace hardcoding of `(0, 0)` with `zero` in `Vector`.

### CODE REVIEW

**Comment by nicoonoclaste** [comment]
`u` and `v` are classical names for those 2 vectors in mathematics; I'm unsure
whether they are the best ones for our users so I asked a computer gfx friend.

**Comment by AstraLuma** [comment]
I'm not immediately thrilled with the names. Why not "x axis" or similar?

**Comment by AstraLuma** [comment]
Also, all three need sphinx-friendly inline docs.

**Comment by nicoonoclaste** [comment]
> I'm not immediately thrilled with the names. Why not "x axis" or similar?

I had discarded `Vector.x` because of the name collision, but yes `x_axis` — or perhaps `x_unit` — would probably be friendlier for neophytes.

**Comment by nicoonoclaste** [comment]
> Also, all three need sphinx-friendly inline docs.

Definitely. I had just skipped it for the time being because I couldn't find how to attach them a docstring, but apparently that's not a thing so I'm making do with the class-level docstring and a bunch of rST markup  :sweat_smile:

**Comment by nicoonoclaste** [comment]
*grumbles about VS Code's search&replace and wonders why `mypy` didn't catch this.*

**Comment by nicoonoclaste** [comment]
Spurious CI failure (fixed in `canon`)

**Comment by AstraLuma** [comment]
Use `#:` per https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

**Comment by nicoonoclaste** [comment]
> Use `#:` per https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

Is that the right thing for class-level variables (as opposed to object-level members) ?

**Comment by AstraLuma** [comment]
Not sure autodoc makes a distinction?

**Comment by pathunstrom** [comment]
Autodoc does not make the distinction.

`#:` is the only way to have autodoc include arbitrary documentation that I've found.

**Comment by nicoonoclaste** [comment]
> Use `#:` per https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

Done.

**Review by AstraLuma — APPROVED** [review]
bors r+

**Comment by AstraLuma** [comment]
bors retry

**Pull request merged**
